repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
        -   id: check-yaml
        -   id: check-toml
#        -   id: end-of-file-fixer
        -   id: trailing-whitespace
#  -   repo: https://github.com/doublify/pre-commit-rust
#      rev: v1.0
#      hooks:
#        - id: fmt
#        - id: cargo-check
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
